apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cloudflared-config
  labels:
{{- include "common.labels" . | nindent 4 }}
data:
  cloudflare-config.yaml: |
    tunnel: k3s
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    no-tls-verify: true
    ingress:
      - hostname: {{ .Values.hostname }}
        service: http://{{ .Release.Name }}-nginx.{{ .Release.Namespace }}.svc.cluster.local:80
      - hostname: grafana.{{ .Values.hostname }}
        service: http://monitoring-grafana.monitoring.svc.cluster.local:80
      - service: http_status:404
