apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cloudflared
  labels:
{{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.4.2
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: credentials
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: {{ .Release.Name }}-secret
        - name: config
          configMap:
            name: {{ .Release.Name }}-cloudflared-config
            items:
              - key: cloudflare-config.yaml
                path: config.yaml
