apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
{{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.credentials | b64enc }}
