apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Files.Get "configs/default.conf" | indent 4}}
