apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitoring.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
{{- include "pi-cluster.labels" . | nindent 4 }}
